# Generated by Django 3.2 on 2022-02-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_analyzer', '0002_searchhistory_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='count',
        ),
    ]
