# Generated by Django 3.2 on 2022-03-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_analyzer', '0002_auto_20220228_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
