# Generated by Django 3.2 on 2022-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_analyzer', '0003_alter_searchhistory_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
